version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres.hrbsivllunsxkqarpxhb
      POSTGRES_PASSWORD: Surajpura@1
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  kraftbase:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres.hrbsivllunsxkqarpxhb:Surajpura@1@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npx prisma migrate deploy && npm start"]

volumes:
  pgdata:
