version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  kraftbase:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npx prisma migrate deploy && npm start"]
    env_file:
      - .env

volumes:
  pgdata:
